name: Check MLB Player Data
on:
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: python check-mlb-player-data.py
      - uses: actions/upload-artifact@v4
        with:
          name: mlb-player-data
          path: check-mlb-player-data.json
